### ISSUE TITLE
On comment color change: TypeError: Cannot read property 'contains' of null

### ISSUE THREAD

**Issue by cclaar-byte** [chrisjpatty/flume#103]
When changing colors in a comment on a fresh install of flume I get the error: TypeError: Cannot read property 'contains' of null.
The code returned is: `   7 | 
   8 | const testClickOutside = React.useCallback(
   9 |   e => {
> 10 |     if (!wrapper.current.contains(e.target)) {
     | ^  11 |       onRequestClose();
  12 |       document.removeEventListener("click", testClickOutside);
  13 |       document.removeEventListener("contextmenu", testClickOutside);`

**Comment by Dante83** [comment]
I also noticed this problem, we might need something like this again?

https://github.com/chrisjpatty/flume/pull/51/files

Alternatively, optional chaining in JS `?.` could be used to return false if any of these elements was null. I notice that the comment does change color, and the panel to change colors disappears, so during the slight lag between these, maybe there is nothing to remove click events from afterwards?

**Comment by Dante83** [comment]
Problem vanished when I upgraded my react app to the latest version today.  Just thought I would mention it here in case someone else is on an older version and is running into this issue. Good luck!

**Comment by chrisjpatty** [comment]
Should be fixed as of v0.7.x
