### ISSUE TITLE
Flume install error

### ISSUE THREAD

**Issue by navanshu** [chrisjpatty/flume#116]
I am getting this error. I don't want to use force command as It might conflict with other npm packages. Please fix this.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: febnikcalculator@7.0.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.13.1" from flume@0.6.3
npm ERR! node_modules/flume
npm ERR!   flume@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by chrisjpatty** [comment]
Thanks for reporting I'll take a look at this. Is this just a clean install in a new project?

**Comment by navanshu** [comment]
It does with npm. If i try run `npm up` it gives the same error. It was installed in the repo before i uninstalled it before updating other libraries.

**Comment by francisbitontistudio** [comment]
I am having this same issue

**Comment by navanshu** [comment]
@francisbitontistudio A temporary fix would be to use npm install hooks, 
```
preinstall: unintsall flume,
postinstall: install flume,
```

I am facing multiple issues with flume on react. I would advise not to update react further V17.0.0

**Comment by silicon-ninja** [comment]
you can install force install the package with this comment ```npm install flume --force```. that works.

**Comment by digichain** [comment]
Same issue.

npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.2" from flume@0.8.0
npm ERR! node_modules/flume
npm ERR!   flume@"*" from the root project

**Comment by atwright147** [comment]
Add the following to `package.json`

```json
  "overrides": {
    "flume": {
      "react": "$react",
      "react-dom": "$react-dom"
    },
    "@reach/utils": {
      "react": "$react",
      "react-dom": "$react-dom"
    }
  }

```
