### ISSUE TITLE
Port names do not render

### ISSUE THREAD

**Issue by ryaninvents** [chrisjpatty/flume#146]
Under ["The Root Node"](https://flume.dev/docs/root-node), it shows how to label ports; however, ports label as their data type (e.g. "True/False") instead of port title (e.g. "Input" or "Output")

```typescript
config.addNodeType({
    type: "boolean",
    label: "True/False",
    description: "Outputs a true/false value",
    initialWidth: 140,
    inputs: ports => [
      ports.boolean({
        name: 'input',
        title: 'Input',
      }),
    ],
    outputs: ports => [
      ports.boolean({
        name: 'input',
        title: 'Input',
      }),
    ]
  })
```

**Comment by chrisjpatty** [comment]
I believe you're just using the wrong key here. If you change it from "title" to "label" does that fix it for you?

**Comment by ryaninvents** [comment]
🤦 Thanks for the quick reply, this was exactly the problem!
