### ISSUE TITLE
Circular/Cyclic Graph Nodes immediately overwhelm the call stack

### ISSUE THREAD

**Issue by alexanderson1993** [chrisjpatty/flume#19]
Hey there. First off, great project. It's amazing, and I'm already thinking of ways to use it.

Secondly, being a hacker, I tried creating a cyclical graph. While the graph could be represented correctly in the graph editor, as soon as it was evaluated by the engine, it created an infinite loop which overloaded the call stack. 

This seems like the kind of thing which could be solved in user land, but I wonder if there are any plans to limit the ability to connect back to a dependency node.

**Comment by chrisjpatty** [comment]
Thanks for bringing this up, this is something I've thought about but haven't settled on the best way to handle it. The problem is that you technically could set up cyclical graphs that **are** valid, as long as the function for one of the nodes in the loop knows to break out it at some point. It would probably be trivial to just track the number of loops in the engine and bail out if it ever gets to some very high number. Maybe that would be a sensible default to have it bailout after like 5000 loops or something, but make it overridable so you can allow infinite loops if you want.

**Comment by alexanderson1993** [comment]
That's what I'm thinking. The ability to do cyclical graphs would be useful in many cases, but having the JS engine choke seems a bad idea. Having Flume handle it makes a lot of sense, especially if you add the iteration configuration option.

**Comment by chrisjpatty** [comment]
Yeah I think you're right. Do you have an opinion on the details of how this exception should be handled? My instinct is to not bail out of the entire `resolveRootNode` function, and instead only bail out of the processing of the current root node input. I have a pending PR that detects circular dependencies per root node input, and throws a descriptive warning, but doesn't crash the engine. That way if you have 5 inputs to the root node, and only one has a circular dependency problem, the values of the remaining 4 ports will still correctly resolve, and the value of the circular port will resolve to undefined and log an error.

<img width="791" alt="Screen Shot 2020-08-06 at 11 22 09 PM" src="https://user-images.githubusercontent.com/14916515/89612017-0020ac00-d83c-11ea-9f67-e9b1792b0d1d.png">
<img width="468" alt="Screen Shot 2020-08-06 at 11 24 15 PM" src="https://user-images.githubusercontent.com/14916515/89612020-03b43300-d83c-11ea-97e3-27af6aa06ca1.png">

**Comment by chrisjpatty** [comment]
I'm toying with the idea of adding this check to the node editor itself as an opt-in validation. That way users could be warned if their node setup would create an infinite loop, or better yet, do the check when connecting a port and prevent the connection if it would result in a cyclical graph. (Also with a warning toast of some kind potentially).

**Comment by alexanderson1993** [comment]
All of this sounds great. Doing the check when making the connection makes the most sense, since it will only happen at that moment instead of multiple times. Doing a recursive check through a large graph could get pretty expensive, so doing it once would keep it fast.

**Comment by chrisjpatty** [comment]
Agreed, I'll merge the engine bailout part of this and then open and link a new issue for doing this check in the editor. Thanks again for bringing this up.
