### ISSUE TITLE
Facing an issue on "TypeError: engine.resolveRootNode is not a function"

### ISSUE THREAD

**Issue by Abhi-Siemens** [chrisjpatty/flume#192]
Hi guys,
I'm facing some issue on **engine.resolveRootNode** is not a function 
this issue is getting based on if ex: if I have created homepage.js component
if I take that page and get in App.js I'm getting this issue 

`import React, { useState } from 'react'
import { useRootEngine } from 'flume'
import engine from '../../engine'

const HomePage = () => {
    const listUser = {
        firstName: 'John',
        lastName: 'Campbell',
        isLoggedIn: true,
        isAdmin: false
    }
    
    const nullUser = {
        firstName: '',
        lastName: '',
        isLoggedIn: false,
        isAdmin: false
    }
    const [user, setUser] = useState(listUser);
    const {
        title,
        description,
        showSignup,
        copyrightYear
      } = useRootEngine(engine, {user})

    const login = () =>  setUser(listUser);
    const logout = () => setUser(nullUser);
  return (
    <div className="homepage">
      <h1 className="title">{title}</h1>
      <p className="description">{description}</p>
      {
        user.isLoggedIn ?
        <button onClick={logout}>Logout</button>
        :
        <button onClick={login}>Login</button>
      }
      {
        showSignup && 
        <form className="signup">
        <input type="email" />
        <button>Signup!</button>
      </form>
      }
      <footer>© flume {copyrightYear}</footer>
    </div>
  )
}

export default HomePage`

**Comment by chrisjpatty** [comment]
It looks like you have a bug in your code there. The first parameter of calling useRootEngine should be your nodes not a reference to the engine. This page of the docs may help:  [using without react](https://flume.dev/docs/using-with-react) I'm also assuming that this is being called inside of a react component? If not you'll need to follow the instructions for [using without react](https://flume.dev/docs/using-without-react).
