### ISSUE TITLE
Type 'string' is not comparable to type 'NodeType'

### ISSUE THREAD

**Issue by Z8MB1E** [chrisjpatty/flume#223]
Hey there, let me start by giving you huge props on an awesome, clean, and useful tool for building flow-based programming node graphs that are compatible with React and, now, TypeScript.

Now onto the bug. While attempting to follow your [tutorial on flume.dev](https://flume.dev/docs/root-engine#setting-up-the-engine), I attempted to verify and implement the necessary types during the process. However, when I got to the `resolveNodes` section, I found that the required type of `NodeResolver` did not allow for its `nodeType` parameter (using the `NodeType` class) to use the following switch statement. See the screenshot below:

![image](https://user-images.githubusercontent.com/5430887/230550851-f5c6520f-20b9-4347-9bf0-b92b6642dbac.png)

The type error disappeared when I replaced `switch (nodeType)` with `switch (nodeType.type)`, but the program ceased functioning. When I switched it back (and once again received the error), the nodegraph started working again.

Any thoughts on this? Thanks again for your help!

**Comment by Z8MB1E** [comment]
Ha, nevermind! It was my own error... I was checking `nodeType` when I should have been checking `node.type`! My apologies - thanks again!

**Comment by chrisjpatty** [comment]
No problem glad you got it sorted out! How has your experience been using the typescript types? Did they feel complete? Would love any feedback on how well they function in practice.
