### ISSUE TITLE
Call-to-Action button is truncated in landing page

### ISSUE THREAD

**Issue by terrytyli** [chrisjpatty/flume#28]
Mac Chrome Version 84.0.4147.89 (Official Build) (64-bit)

See screenshot below.

![image](https://user-images.githubusercontent.com/29028851/90081934-e27aa780-dd51-11ea-924b-64400775d4cb.png)

If I increase the min-height of this class it will work

```
.heroBlock_3SLJ {
     display: flex;
     width: 100%;
     min-height: calc(100vh - 40px);
     background: var(--background-dark);
}

```

**Comment by chrisjpatty** [comment]
Oh thanks for reporting this, looks like it doesn't handle the window being too short.

**Comment by terrytyli** [comment]
Mine is a 13'' Mac book. 

It is not really too short.

Please see screenshot below.

![image](https://user-images.githubusercontent.com/29028851/90082472-35089380-dd53-11ea-8d3d-5f22e54691c8.png)

**Comment by chrisjpatty** [comment]
Thanks again, I've pushed a fix for this.
