### ISSUE TITLE
Dynamically generate inputs based on node content

### ISSUE THREAD

**Issue by numso** [chrisjpatty/flume#32]
I'm trying to create a `compose` node that takes a string of parameterized text and lets you plug in the variables. For example, I may want to generate an email message like: `Welcome {name}, your document is ready at {url}.`. This is possible today by defining the JoinStrings node found in the examples and using it a bunch of times. Ideally it could be a single node, I could type this in as my node's first input, and 2 string inputs would be auto-generated on the side: `name` and `url`.

**Comment by andraz-at** [comment]
I have a similar need with boolean AND & OR logical blocks. They will work the same no matter how many inputs you have, but they need to have all inputs connected, else they don't make much sense.

Having a way to dynamically define those input ports would be a great feature.

Alternative option to do the same would be to have a "multi-input" port which expects an array of inputs. If you connect 3 outputs to this input you'd get `[output1,output2,output3]` on that input. Port could be defined as an "array" input.
