### ISSUE TITLE
Nested nodes?

### ISSUE THREAD

**Issue by boticello** [chrisjpatty/flume#36]
Nice-looking library! Congratulations. 

Do you have any thoughts or intentions around nodes which are composed of their own graph of nodes? The use cases I have in mind would benefit from this ability to nest, modularize, and hide complexity.

**Comment by chrisjpatty** [comment]
Thanks! It's definitely on the road-map at some point. Some of the initial focus is to ensure the current feature set is fully stable, and get automated tests in place so there's a solid foundation to build new features on like this. In the meantime though, there's a roundabout way you can actually support a version of nested nodes. Essentially you can provide a UI for users to create logic graphs with defined inputs and outputs of the node "group", and then you can allow them to reference those logic graphs in a different node editor. This isn't an ideal setup, and there's already some work going on to improve that workflow, but at some point I'd like node groups to be a first-class citizen of the library.

**Comment by boticello** [comment]
Yes, thanks for the tip @chrisjpatty. I was thinking along those lines myself. It is a bit of work to get the right UI. Great to hear that it's on the roadmap. I'll focus on simpler use cases for the moment.
