### ISSUE TITLE
Is there functionality to restore Nodes?

### ISSUE THREAD

**Issue by netgfx** [chrisjpatty/flume#46]
I read this: https://flume.dev/docs/saving-nodes but not sure how we can restore the saved nodes. Imagine the following scenario: 
- Save nodes
- Save them as JSON in local-storage
- Refresh page
- Restore nodes from local-storage

Is there any way to achieve this?

**Comment by chrisjpatty** [comment]
Yes, you can start the node editor with any set of nodes. This is a pretty simple setup, here's a code sandbox with an example for you: [https://codesandbox.io/s/flume-nodes-in-local-storage-u78ek?file=/src/App.js](https://codesandbox.io/s/flume-nodes-in-local-storage-u78ek?file=/src/App.js)

**Comment by netgfx** [comment]
awesome thanks!

**Comment by netgfx** [comment]
@chrisjpatty One more thing I noticed that this setup doesn't also save comments, can I do the same thing with comments as well?

**Comment by chrisjpatty** [comment]
@netgfx Yep! Just use the `getComments()` function and store them in the same way. Comments are kept in a separate data structure from the nodes because they are purely informational.

**Comment by netgfx** [comment]
Yup thanks got it working!
