### ISSUE TITLE
Ability to enhance the node header

### ISSUE THREAD

**Issue by numso** [chrisjpatty/flume#56]
It would be awesome if flume exposed some way to customize what shows up in a node's header.

I'm trying to add an icon to the top right of each of my nodes (which on hover/click will show some help text/video). I can kinda hack it together by setting my node's label to be a React element but it's got some issues:

1. That icon also shows up in the node list. This may or may not be desirable.
2. Typing in the "Filter Options" sections causes a crash because label is expected to be a string.

![image](https://user-images.githubusercontent.com/1761757/98413624-2d494a00-2037-11eb-9ee7-5239e221eed1.png)

![image](https://user-images.githubusercontent.com/1761757/98414039-e3149880-2037-11eb-8998-827029f3bed3.png)

**Comment by chrisjpatty** [comment]
I really like this idea and I've heard similar requests. What if we provided a prop on the nodeEditor like `renderNodeHeader` or something like that, that would give you the current node type, and you could return your own custom header with whatever interactive elements you want? I think in my mind that covers this in a fairly generic/un-opinionated way.

**Comment by ryaninvents** [comment]
I like the `renderNodeHeader` idea. When deciding on props, I think it would be useful to include a reference to the node itself. One of my nodes has a large editor that's too complex to fit into the limited space available, so I would want to allow uses to click the node header to open a modal.

**Comment by chrisjpatty** [comment]
This is now available in version 0.7.1 !
