### ISSUE TITLE
Get values of nodes with click

### ISSUE THREAD

**Issue by CyrilDelvalle** [chrisjpatty/flume#60]
Hey, I am looking for a solution to be able to dynamically retrieve the nodes that have been added. 
Because I want to get each values of my node when I click on, like label etc..
Anyone knows how can I do that ?
Thank you very much for your answers !

**Comment by chrisjpatty** [comment]
Hey @CyrilDelvalle! Can you tell me a little more about what you're trying to build? When you say you want to get the value of a node, do you mean the values of its ports? Currently the built-in way to get the nodes is using the [`onChange` function of the node editor](https://flume.dev/docs/saving-nodes#onchange), or the [`getNodes` function available on the nodeEditor ref](https://flume.dev/docs/saving-nodes#getnodes).

**Comment by CyrilDelvalle** [comment]
I'm looking for show/hide a pop-up with the infos about the node that was cliked, like all labels, ports etc...
