### ISSUE TITLE
Context menu breaks with MaterialUI Select component

### ISSUE THREAD

**Issue by rgngl** [chrisjpatty/flume#70]
When having a Material UI [Select](https://material-ui.com/components/selects/) component on the same page with a flume NodeEditor, after opening the select popover once, the NodeEditor context menu stops working.

As a React newbie, my skills for debugging this further are limited. Nevertheless, here's a reproduction case:
https://codepen.io/rgngl/pen/poEZdQb

**Comment by chrisjpatty** [comment]
@rgngl Thanks for reporting this and for the Codepen! Yeah it looks like our two libraries aren't playing super nice for some reason. I'll spin through this and see if there's something obvious I can fix this weekend.

**Comment by chrisjpatty** [comment]
@rgngl I've been investigating this on and off for a couple weeks and I think I've discovered that it's a problem with React 17's new event handling model. But there should be a workaround I think.  I'll know more on that soon.

**Comment by chrisjpatty** [comment]
@rgngl Just got it figured out. This should now be fixed in version 0.6.3 with #72. I'm going to close this for now, but let me know if you're still having trouble on your end.

**Comment by rgngl** [comment]
Great! Thank you very much!
